name: Compilation STM32

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Récupérer le code
      uses: actions/checkout@v4

    - name: ⚙️ Installer la Toolchain ARM
      uses: carlosperate/arm-none-eabi-gcc-action@v1
      with:
        release: '12.2.Rel1'

    - name: 🚀 Lancer la compilation
      run: make -j$(nproc)

    - name: 💾 Sauvegarder le Firmware compilé (Artefact)
      uses: actions/upload-artifact@v4
      with:
        name: FADEC-Firmware
        path: build/